export const MAX_SLOTS = 24;
export const REGISTRATION_OPEN_HOUR = 12; // 12:00 PM noon
export const REGISTRATION_OPEN_MINUTE = 0;
export const REGISTRATION_CLOSE_HOUR = 19;
export const REGISTRATION_CLOSE_MINUTE = 30; // 7:30 PM
export const CANCELLATION_CLOSE_HOUR = 19; // 7:00 PM
export const CANCELLATION_CLOSE_MINUTE = 0;
