import { User, GameDay, BlockedDate } from "./types";
import { getLast12Months, getTodayDate } from "./utils";

function makePaymentHistory(paidMonths: number[]): { month: string; paid: boolean }[] {
  const months = getLast12Months();
  return months.map((month, i) => ({
    month,
    paid: paidMonths.includes(i),
  }));
}

export const mockUsers: User[] = [
  {
    id: "u1",
    username: "admin",
    password: "admin123",
    fullName: "Ricardo Reyes",
    firstName: "Ricardo",
    lastName: "Reyes",
    email: "ricardo.reyes@lamarea.ph",
    mobile: "09171234567",
    address: "Block 1 Lot 5, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "admin",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
    noShowCount: 0,
    acceptedTerms: true,
    createdAt: "2025-06-01",
  },
  {
    id: "u2",
    username: "maria.santos",
    password: "password",
    fullName: "Maria Santos",
    firstName: "Maria",
    lastName: "Santos",
    email: "maria.santos@gmail.com",
    mobile: "09181234567",
    address: "Block 2 Lot 10, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
    noShowCount: 1,
    acceptedTerms: true,
    createdAt: "2025-07-15",
  },
  {
    id: "u3",
    username: "juan.cruz",
    password: "password",
    fullName: "Juan Cruz",
    firstName: "Juan",
    lastName: "Cruz",
    email: "juan.cruz@gmail.com",
    mobile: "09191234567",
    address: "Block 3 Lot 8, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: false,
    paymentHistory: makePaymentHistory([1, 2, 3, 5, 6, 7, 9, 10]),
    noShowCount: 3,
    acceptedTerms: true,
    createdAt: "2025-08-01",
  },
  {
    id: "u4",
    username: "ana.garcia",
    password: "password",
    fullName: "Ana Garcia",
    firstName: "Ana",
    lastName: "Garcia",
    email: "ana.garcia@gmail.com",
    mobile: "09201234567",
    address: "Block 4 Lot 3, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
    noShowCount: 0,
    acceptedTerms: true,
    createdAt: "2025-07-20",
  },
  {
    id: "u5",
    username: "carlos.deleon",
    password: "password",
    fullName: "Carlos De Leon",
    firstName: "Carlos",
    lastName: "De Leon",
    email: "carlos.deleon@gmail.com",
    mobile: "09211234567",
    address: "Block 5 Lot 12, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11]),
    noShowCount: 2,
    acceptedTerms: true,
    createdAt: "2025-09-10",
  },
  {
    id: "u6",
    username: "sofia.ramos",
    password: "password",
    fullName: "Sofia Ramos",
    firstName: "Sofia",
    lastName: "Ramos",
    email: "sofia.ramos@gmail.com",
    mobile: "09221234567",
    address: "Block 1 Lot 15, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11]),
    noShowCount: 0,
    acceptedTerms: true,
    createdAt: "2025-10-05",
  },
  {
    id: "u7",
    username: "miguel.villanueva",
    password: "password",
    fullName: "Miguel Villanueva",
    firstName: "Miguel",
    lastName: "Villanueva",
    email: "miguel.v@gmail.com",
    mobile: "09231234567",
    address: "Block 6 Lot 7, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
    noShowCount: 1,
    acceptedTerms: true,
    createdAt: "2025-11-01",
  },
  {
    id: "u8",
    username: "isabella.mendoza",
    password: "password",
    fullName: "Isabella Mendoza",
    firstName: "Isabella",
    lastName: "Mendoza",
    email: "isabella.m@gmail.com",
    mobile: "09241234567",
    address: "Block 2 Lot 20, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: false,
    paymentHistory: makePaymentHistory([1, 2, 4, 5, 7, 8, 10]),
    noShowCount: 5,
    acceptedTerms: true,
    createdAt: "2025-12-01",
  },
  {
    id: "u9",
    username: "rafael.aquino",
    password: "password",
    fullName: "Rafael Aquino",
    firstName: "Rafael",
    lastName: "Aquino",
    email: "rafael.aquino@gmail.com",
    mobile: "09251234567",
    address: "Block 7 Lot 2, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),
    noShowCount: 0,
    acceptedTerms: true,
    createdAt: "2026-01-15",
  },
  {
    id: "u10",
    username: "elena.bautista",
    password: "password",
    fullName: "Elena Bautista",
    firstName: "Elena",
    lastName: "Bautista",
    email: "elena.b@gmail.com",
    mobile: "09261234567",
    address: "Block 3 Lot 18, La Marea",
    laMareaIdUrl: "/placeholder-id.jpg",
    registrationFeeUrl: "/placeholder-receipt.jpg",
    role: "member",
    isPaid: true,
    paymentHistory: makePaymentHistory([0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11]),
    noShowCount: 1,
    acceptedTerms: true,
    createdAt: "2026-02-01",
  },
];

const today = getTodayDate();

// Pre-populate 18 registered players from paid users + some extras
const registeredPlayerNames = [
  { userId: "u2", fullName: "Maria Santos" },
  { userId: "u4", fullName: "Ana Garcia" },
  { userId: "u5", fullName: "Carlos De Leon" },
  { userId: "u6", fullName: "Sofia Ramos" },
  { userId: "u7", fullName: "Miguel Villanueva" },
  { userId: "u9", fullName: "Rafael Aquino" },
  { userId: "u10", fullName: "Elena Bautista" },
  { userId: "u1", fullName: "Ricardo Reyes" },
  { userId: "ext1", fullName: "Paolo Navarro" },
  { userId: "ext2", fullName: "Carmen Lim" },
  { userId: "ext3", fullName: "Diego Fernandez" },
  { userId: "ext4", fullName: "Patricia Tan" },
  { userId: "ext5", fullName: "Marco Aguilar" },
  { userId: "ext6", fullName: "Teresa Gomez" },
  { userId: "ext7", fullName: "Antonio Castillo" },
  { userId: "ext8", fullName: "Lucia Morales" },
  { userId: "ext9", fullName: "Gabriel Pascual" },
  { userId: "ext10", fullName: "Rosa Dizon" },
];

const waitlistNames = [
  { userId: "ext11", fullName: "Andres Salazar" },
  { userId: "ext12", fullName: "Beatriz Ocampo" },
  { userId: "ext13", fullName: "Fernando Lacson" },
];

export const mockGameDay: GameDay = {
  date: today,
  isBlocked: false,
  blockMessage: null,
  registeredPlayers: registeredPlayerNames.map((p, i) => ({
    ...p,
    registeredAt: new Date(
      new Date().setHours(12, i * 2, 0, 0)
    ).toISOString(),
  })),
  waitlist: waitlistNames.map((p, i) => ({
    ...p,
    registeredAt: new Date(
      new Date().setHours(12, 40 + i * 3, 0, 0)
    ).toISOString(),
  })),
  noShows: [],
};

// Past game days for calendar history
function makePastGameDay(date: string, playerCount: number, noShowIds: string[] = []): GameDay {
  const pool = [
    { userId: "u2", fullName: "Maria Santos" },
    { userId: "u4", fullName: "Ana Garcia" },
    { userId: "u5", fullName: "Carlos De Leon" },
    { userId: "u6", fullName: "Sofia Ramos" },
    { userId: "u7", fullName: "Miguel Villanueva" },
    { userId: "u9", fullName: "Rafael Aquino" },
    { userId: "u10", fullName: "Elena Bautista" },
    { userId: "u1", fullName: "Ricardo Reyes" },
    { userId: "ext1", fullName: "Paolo Navarro" },
    { userId: "ext2", fullName: "Carmen Lim" },
    { userId: "ext3", fullName: "Diego Fernandez" },
    { userId: "ext4", fullName: "Patricia Tan" },
    { userId: "ext5", fullName: "Marco Aguilar" },
    { userId: "ext6", fullName: "Teresa Gomez" },
    { userId: "ext7", fullName: "Antonio Castillo" },
    { userId: "ext8", fullName: "Lucia Morales" },
    { userId: "ext9", fullName: "Gabriel Pascual" },
    { userId: "ext10", fullName: "Rosa Dizon" },
    { userId: "ext11", fullName: "Andres Salazar" },
    { userId: "ext12", fullName: "Beatriz Ocampo" },
    { userId: "ext13", fullName: "Fernando Lacson" },
    { userId: "u3", fullName: "Juan Cruz" },
    { userId: "u8", fullName: "Isabella Mendoza" },
    { userId: "ext14", fullName: "Ramon Torres" },
  ];
  return {
    date,
    isBlocked: false,
    blockMessage: null,
    registeredPlayers: pool.slice(0, playerCount).map((p, i) => ({
      ...p,
      registeredAt: new Date(date + "T12:00:00").toISOString(),
    })),
    waitlist: [],
    noShows: noShowIds,
  };
}

export const mockGameDays: Record<string, GameDay> = {
  "2026-03-28": makePastGameDay("2026-03-28", 20, ["u3"]),
  "2026-03-29": makePastGameDay("2026-03-29", 16),
  "2026-03-31": makePastGameDay("2026-03-31", 22, ["u8", "ext5"]),
  "2026-04-01": makePastGameDay("2026-04-01", 24, ["u3", "u8"]),
  "2026-04-02": makePastGameDay("2026-04-02", 19, ["ext2"]),
  [today]: mockGameDay,
};

export const mockBlockedDates: BlockedDate[] = [
  { date: "2026-04-10", message: "Court maintenance — resurfacing in progress" },
  { date: "2026-04-15", message: "Typhoon warning — Severe Weather Alert" },
];
